travis:
  secure:
    BINSTAR_TOKEN: qiwcwvdyxYpem2SOIv5EOvgkli/oF+BySP81JgTS/RGz08QuGTrJZpISjrYFhbhOucgaMr01+ZAS3X9zu6cY+/Ld40N5SmCDpiuX9H3sIIlmpydYZlUzk/ilbQyu2N/z9l1Lw9la8Nas4hQY7M3Kpcb97d0FJgjrxtc8UAko2Ce1upU1Dzqzj1tdqn0u/C047+0GaHp5PKaV0lHQqepF94oMuJOg9ZWF1/Ov6E2EFC7Wii8eJTU16TtmS6O/Coq+WtHx67YPligxQJfcZ6xT8+9NEQpGqkU2mAZY3qm3CUFPARnWpVEmVytI6aPFTRQFZOrZl6mpwUJUKELd/M+/Eotq/MWsmu8LCdWzBo+LVf+AjmxI9QbKPxxzCH7hdyxutBjXXnuzOU0N4lTC8kFO9gCuEOItF/6MOkCVT0IxbbizZCBT4LLqVoGF5Q3WCAvhmfdu1JskcuEbplgT3kouXLfHsvRty3mstHo79XKJgBp9IENosE2Qb+DXEkihhs6HAV9dYxxKcmt9wzi5pWz9DdkQefgDcByPu7VRXJmlm/PAjc7yR7WKUYgPhJVPDwrMbiG42o7RsMYk5000HlhezPz2R8j91DrCpoe4jmrk8ZvdUGDTuUzUETMmuLeVDwobhQpUWNCTKdSX+srpXmMXCMyZBNkp7bU61f28RKRhAYQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
