travis:
  secure:
    BINSTAR_TOKEN: bGghGWq0G7mx1A7hGtqW7NGE1/csMZAwsvwqLVg0sgNf+NxPl6jTSztG6aGqrmMcZ/jkHPROwQwUBPSWrnTcs5xyuwuQJUh9HVJcP2PA4u1N8Qoh2uNW74RS7n7hth4P0hTU9hUIrdphhe5/Is8npkD4L0DW+2JICnGvcMfiSU3F9R3yabPiA1mkxSuC/kMrAocGXofSav7RBFccekMIRWQ60gWF1r/Pp2mDXZQf/tICw1CJIkDQsXoGb4W6nQ5fuTmlDsxX+TTKAuNpBXoNNwI2m5wD7tsc15seY5TD88IDrpABHetz8ytswZ+b/Yj6dhjbv+UV5aVDzq6YMkjY9McOZM16XCG9dhZKn6hjKTsEFNLFQ+YzM81EaFmjSKQlrJbMGryzns7Q7V7jbz1Dw3Q3RAXy3ZDg4W8/JbD0Sv56yIq8dOLkMgL2B61EyU3NwG4OsTMLmmYHH2o8a5dJ2dfVWwx6bIlk9hmFhMHFicYq3Pz92xleh557ZACLdVJqMpZFnJd1lo3iBr1TUh3MzL57V4NL9gJ0p9kcbKPSk7aOAbw4qRHsIzN+JLZpWeuQhPIys8mudsQ8ezvoeiE2MNyXm2lLAmwlbFaAtqX6YgyFyHlF1XMj6z78wUsRHwmqwejqXxo7aLyP9QcgY3ZcLDEDKjUP2aLS2L8crcVGE94=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
